#! /usr/bin/env bash

set -e

if command -v swiftformat >/dev/null 2>&1; then
  swiftformat --config .swiftformat .
else
  echo "warning: Install swiftformat by running 'brew install swiftformat'"
fi
